# Generated by Django 2.2.19 on 2022-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
